name: Build

on:
  push:
    tags:
      - '*'
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          **/go.sum
          **/go.mod
          ${{ github.workspace }}/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go

    - name: Get dependencies
      run: go mod tidy

    - name: Format code
      run: gofmt -s -w .

    - name: Run tests
      run: go test ./...

    - name: Build
      run: go build -o bin/album2go ./src

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: album2go
        path: bin/album2go

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: "Build: ${{ env.GITHUB_HEAD_REF_SLUG }} ${{ env.GITHUB_SHA_SHORT }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        allowUpdates: false       

    - name: Upload binary to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bin/album2go
        asset_name: album2go
        asset_content_type: application/octet-stream
